<h1>Chapter 7: Data cleaning and Preparation </h1>
<h2>    Section 1: Handling missing data </h2>


In [1]:
import pandas as pd
import numpy as np
import pyarrow
import re

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [3]:
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()


0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])

In [6]:
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [7]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [8]:
float_data  = pd.Series([1, 2, None], dtype="float64")

In [9]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [10]:
float_data.dropna()

0    1.0
1    2.0
dtype: float64

In [11]:
string_data.dropna()

0    aardvark
3     avocado
dtype: object

In [12]:
string_data.fillna("spam")

0    aardvark
1        spam
2        spam
3     avocado
dtype: object

<h3>Filtering Out Missing Data</h3>

In [13]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [14]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

<body>The longer method below is equivalent to dropna</body>

In [15]:
data[data.notna()] 

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [19]:
data.dropna(how="all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [20]:
data[4] = np.nan

In [21]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [22]:
data.dropna(how="all", axis="columns")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [23]:
df = pd.DataFrame(np.random.standard_normal((7,3)))

In [24]:
df.iloc[:4,1] = np.nan

In [25]:
df.iloc[:2, 2] = np.nan

In [26]:
df

0         1         2
0  0.672827       NaN       NaN
1 -3.276517       NaN       NaN
2  0.142542       NaN  1.121634
3  0.112440       NaN  1.220112
4  1.038318  0.419774  2.472756
5  1.398026  0.605769  0.763275
6  0.901032 -0.628200  0.588936

In [27]:
df.dropna()

0         1         2
4  1.038318  0.419774  2.472756
5  1.398026  0.605769  0.763275
6  0.901032 -0.628200  0.588936

In [28]:
df.dropna(thresh=2)

0         1         2
2  0.142542       NaN  1.121634
3  0.112440       NaN  1.220112
4  1.038318  0.419774  2.472756
5  1.398026  0.605769  0.763275
6  0.901032 -0.628200  0.588936

<h3>Filling In Missing Data</h3>

In [29]:
df.fillna(0)

0         1         2
0  0.672827  0.000000  0.000000
1 -3.276517  0.000000  0.000000
2  0.142542  0.000000  1.121634
3  0.112440  0.000000  1.220112
4  1.038318  0.419774  2.472756
5  1.398026  0.605769  0.763275
6  0.901032 -0.628200  0.588936

In [30]:
df.fillna({1:0.5, 2:0})

0         1         2
0  0.672827  0.500000  0.000000
1 -3.276517  0.500000  0.000000
2  0.142542  0.500000  1.121634
3  0.112440  0.500000  1.220112
4  1.038318  0.419774  2.472756
5  1.398026  0.605769  0.763275
6  0.901032 -0.628200  0.588936

In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [32]:
df

0         1         2
0  0.332838  1.015896 -1.411432
1 -1.078902  1.137679 -2.341289
2 -0.800590  0.579818  0.011952
3  0.512489 -1.618336 -1.096284
4  0.421544 -1.741290  0.664973
5  1.594548  1.177390 -1.908114

In [33]:
df.iloc[2:, 1] = np.nan

In [34]:
df.iloc[4:,2] = np.nan

In [35]:
df.fillna(method="ffill")

/tmp/ipykernel_5727/3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")


0         1         2
0  0.332838  1.015896 -1.411432
1 -1.078902  1.137679 -2.341289
2 -0.800590  1.137679  0.011952
3  0.512489  1.137679 -1.096284
4  0.421544  1.137679 -1.096284
5  1.594548  1.137679 -1.096284

In [36]:
df.ffill()

0         1         2
0  0.332838  1.015896 -1.411432
1 -1.078902  1.137679 -2.341289
2 -0.800590  1.137679  0.011952
3  0.512489  1.137679 -1.096284
4  0.421544  1.137679 -1.096284
5  1.594548  1.137679 -1.096284

In [37]:
df.ffill(limit=2)

0         1         2
0  0.332838  1.015896 -1.411432
1 -1.078902  1.137679 -2.341289
2 -0.800590  1.137679  0.011952
3  0.512489  1.137679 -1.096284
4  0.421544       NaN -1.096284
5  1.594548       NaN -1.096284

In [38]:
df

0         1         2
0  0.332838  1.015896 -1.411432
1 -1.078902  1.137679 -2.341289
2 -0.800590       NaN  0.011952
3  0.512489       NaN -1.096284
4  0.421544       NaN       NaN
5  1.594548       NaN       NaN

In [39]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [40]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [41]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

<h2>7.2 Data Transformation</h2>

<h3>Removing Duplicates</h3>

In [42]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"], "k2":[1, 1, 2, 3, 3, 4, 4]})

In [43]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [44]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [45]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [46]:
data["v1"] = range(7)

In [47]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [48]:
data.drop_duplicates(subset="k1")

k1  k2  v1
0  one   1   0
1  two   1   1

In [49]:
data.drop_duplicates(subset=["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

<h3>Tranforming Data Using a Function or Mapping</h3>

In [50]:
data = pd.DataFrame({"food":["bacon", "pulled pork", "bacon",
                             "pastrami", "corned beef", "bacon", 
                             "pastrami", "honey ham", "nova lox"], 
                     "ounces":[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [51]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [52]:
meat_to_animal =  {"bacon": "pig",
                   "pulled pork": "pig",
                   "pastrami": "cow",
                   "corned beef": "cow",
                   "honey ham": "pig",
                   "nova lox": "salmon",}

In [53]:
data["animal"] = data["food"].map(meat_to_animal)

In [54]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [55]:
def get_animal(x):
    return meat_to_animal[x]

In [56]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

<h3 style="color:blue">Replacing Values</h3>

In [57]:
data = pd.Series([1., -999., 2., -999., -1000., 3.,])

In [58]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [59]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [60]:
data.replace([-999., -1000.], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [61]:
data.replace([-999., -1000.], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [62]:
data.replace({-999.: np.nan, -1000.: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

<h3 style="color:blue">Renaming Axis Indexes</h3>

In [63]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "California", "New York"],
                    columns=["one", "two", "three", "four"])

In [64]:
data

one  two  three  four
Ohio          0    1      2     3
California    4    5      6     7
New York      8    9     10    11

In [65]:
def transform(x):
    return x[:4].upper()

In [66]:
data.index.map(transform)

Index(['OHIO', 'CALI', 'NEW '], dtype='object')

In [67]:
data.index = data.index.map(transform)

In [68]:
data

one  two  three  four
OHIO    0    1      2     3
CALI    4    5      6     7
NEW     8    9     10    11

In [69]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Cali    4    5      6     7
New     8    9     10    11

In [70]:
data.rename(index={"OHIO": "INDIANA", "CALI": "COLO"},
            columns={"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

<h3 style="color:blue">Discretizing and Binning</h3>

In [71]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [72]:
bins = [18, 25, 35, 60, 100]

In [73]:
age_categories = pd.cut(ages, bins)

In [74]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [75]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [76]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [77]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [78]:
age_categories.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [79]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [80]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [81]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [82]:
data = np.random.uniform(size=20)

In [83]:
quartiles = pd.cut(data, 4, precision=2)

In [84]:
quartiles

[(0.084, 0.31], (0.084, 0.31], (0.084, 0.31], (0.31, 0.53], (0.31, 0.53], ..., (0.75, 0.97], (0.75, 0.97], (0.75, 0.97], (0.75, 0.97], (0.53, 0.75]]
Length: 20
Categories (4, interval[float64, right]): [(0.084, 0.31] < (0.31, 0.53] < (0.53, 0.75] < (0.75, 0.97]]

In [85]:
quartiles.value_counts()

(0.084, 0.31]    5
(0.31, 0.53]     3
(0.53, 0.75]     4
(0.75, 0.97]     8
Name: count, dtype: int64

In [86]:
data = np.random.standard_normal(1_000)

In [87]:
quartiles =  pd.qcut(data, 4, precision=2)

In [88]:
quartiles

[(-2.67, -0.66], (-0.037, 0.69], (-0.037, 0.69], (0.69, 3.09], (-0.66, -0.037], ..., (0.69, 3.09], (-0.66, -0.037], (-0.66, -0.037], (-0.66, -0.037], (-0.66, -0.037]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.67, -0.66] < (-0.66, -0.037] < (-0.037, 0.69] < (0.69, 3.09]]

In [89]:
quartiles.value_counts()

(-2.67, -0.66]     250
(-0.66, -0.037]    250
(-0.037, 0.69]     250
(0.69, 3.09]       250
Name: count, dtype: int64

In [90]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.659, -1.252]     100
(-1.252, -0.0371]    400
(-0.0371, 1.32]      400
(1.32, 3.092]        100
Name: count, dtype: int64

<h3 style="color:blue">Detecting and Filtering Outliers</h3>

In [91]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.018322    -0.044782    -0.033388     0.030473
std       0.970035     0.971972     0.940082     1.047937
min      -2.755502    -3.981076    -2.836304    -3.120968
25%      -0.679901    -0.678386    -0.638605    -0.685220
50%      -0.016063    -0.080524    -0.024428     0.028595
75%       0.635323     0.597666     0.579888     0.741426
max       3.378249     4.010122     2.497907     3.705884

In [93]:
col=data[2]

In [94]:
col[col.abs() > 3]

Series([], Name: 2, dtype: float64)

In [95]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
75   3.378249  1.384336  0.542330 -1.758835
133 -0.898594 -0.920721  0.326170  3.109295
236 -0.075219 -0.639954  0.872107 -3.120968
283  0.548930  3.506524 -0.056460 -1.053901
310 -1.521593 -0.005792 -1.189240  3.705884
447  0.329718 -3.024290  0.361193 -0.419274
522  0.373770  3.115882  1.078451  0.724621
531  3.129803 -0.971030  0.457939  0.622343
570 -1.971835  0.881179 -0.790202  3.014370
864 -0.507176  4.010122  0.745109 -0.353743
892 -2.011154 -0.228913 -0.359625 -3.118477
904 -0.697710 -3.981076 -1.835048 -1.250206
947 -0.613198  0.919934  0.016257 -3.104147

In [96]:
data[data.abs() > 3] = np.sign(data) * 3

In [97]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.018830    -0.045409    -0.033388     0.029987
std       0.968368     0.962587     0.940082     1.044320
min      -2.755502    -3.000000    -2.836304    -3.000000
25%      -0.679901    -0.678386    -0.638605    -0.685220
50%      -0.016063    -0.080524    -0.024428     0.028595
75%       0.635323     0.597666     0.579888     0.741426
max       3.000000     3.000000     2.497907     3.000000

In [98]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4  1.0  1.0 -1.0 -1.0

<h3 style="color:blue">Permutations and Random Sampling</h3>

In [99]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [100]:
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [101]:
sampler = np.random.permutation(5)

In [102]:
sampler

array([1, 4, 0, 3, 2])

In [103]:
df.take(sampler)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [104]:
df.iloc[sampler]

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [105]:
column_sampler = np.random.permutation(7)

In [106]:
column_sampler

array([1, 3, 2, 5, 6, 4, 0])

In [107]:
df.take(column_sampler, axis="columns").take(sampler)

1   3   2   5   6   4   0
1   8  10   9  12  13  11   7
4  29  31  30  33  34  32  28
0   1   3   2   5   6   4   0
3  22  24  23  26  27  25  21
2  15  17  16  19  20  18  14

In [108]:
df.sample(n=3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [109]:
choices = pd.Series([5, 7, -1, 6, 4])

In [110]:
choices.sample(n=10, replace=True)

2   -1
1    7
4    4
2   -1
4    4
0    5
1    7
3    6
0    5
3    6
dtype: int64

<h3 style='color:blue'>Computing Indicator/Dummy Variables</h3>

In [111]:
df = pd.DataFrame({"key":["b", "b", "a", "c", "a", "b"],
              "data1":range(6)})

In [112]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [113]:
pd.get_dummies(df["key"], dtype=int )

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [114]:
dummies = pd.get_dummies(df["key"], prefix="key")

In [115]:
df_with_dummy = df[["data1"]].join(dummies)

In [116]:
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [117]:
mnames= ["movie_id", "title",  "genres"]

In [118]:
movies = pd.read_table("../datasets/movielens/movies.dat", sep="::",
                      header=None, names=mnames, engine="python")

In [119]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [120]:
dummies = movies["genres"].str.get_dummies("|")

In [121]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [122]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [123]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [124]:
np.random.seed(12345) # To make example repeatable

In [125]:
values = np.random.uniform(size=10).round(4)

In [126]:
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [127]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [128]:
pd.get_dummies(pd.cut(values, bins), dtype=int)

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

<h2 style="color:purple"> 7.3 Extension Data Types</h2>

In [130]:
s = pd.Series([1, 2, 3, None])

In [131]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [132]:
s.dtype

dtype('float64')

In [135]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [136]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [138]:
s.dtype

Int64Dtype()

In [140]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [141]:
s[3]

<NA>

In [142]:
s[3] is pd.NA

True

<p style="color:red">Note: The capitalization of 'Int64' in 'pd.Int64Dtype' or the shorthand 'Int64' is necessary for it to be a pandas extension type.</p>

In [144]:
s = pd.Series([1, 2, 3, None], dtype='Int64')

In [150]:
s = pd.Series(["one", "two", None, "three"], dtype=pd.StringDtype())

In [151]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [153]:
df = pd.DataFrame({"A":[1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

In [154]:
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [155]:
df["A"] = df["A"].astype("Int64")

In [156]:
df["B"] = df["B"].astype("string")

In [157]:
df["C"] =df["C"].astype("boolean")

In [158]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

<h2 style="color:purple">7.4 String Manipulation</h2>

<h3 style="color:blue">Python Built-In String Object Methods</h3>

In [159]:
val = "a,b, guido"

In [160]:
val.split(",")

['a', 'b', ' guido']

In [161]:
pieces = [x.strip() for x in val.split(",")]

In [162]:
pieces

['a', 'b', 'guido']

In [163]:
first, second, third = pieces

In [164]:
first + "::" + second + "::" + third

'a::b::guido'

In [165]:
"::".join(pieces)

'a::b::guido'

In [167]:
"guido" in val

True

In [176]:
val.index(",") # obj.index() raises ValueError exception if substring is not found

1

In [177]:
val.find(":") # obj.find() does not raise an exception if substring not found, returns -1

-1

In [182]:
val.count(",")

2

In [183]:
val.replace(",", ":")

'a:b: guido'

In [184]:
val.replace(",", "")

'ab guido'

<h3 style="color:purple">Regular Expressions</h3>

In [3]:
text = "foo  bar\t baz  \tqux"

In [4]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [7]:
regex = re.compile(r"\s+")

In [10]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [11]:
regex.findall(text)

['  ', '\t ', '  \t']

In [18]:
text = """Dave dave@google.com
Steve steve@gmail.com 
Rob rob@gmail.com
Ryan ryan@gmail.com"""

pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

regex = re.compile(pattern, flags=re.IGNORECASE)

In [19]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@gmail.com']

In [21]:
m = regex.search(text)

In [22]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [24]:
text[m.start():m.end()]

'dave@google.com'

In [25]:
print(regex.match(text))

None


In [27]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED 
Rob REDACTED
Ryan REDACTED


In [191]:
    pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [192]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [193]:
m = regex.match("wesm@bright.net")

In [194]:
m.groups()

('wesm', 'bright', 'net')

In [195]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'gmail', 'com')]

In [196]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com 
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: gmail, Suffix: com


<h3 style="color:purple">String Functions in pandas</h3>

In [3]:
data = {"Dave": "dave@google.com", 
        "Steve": "steve@google.com",
        "Rob": "rob@google.com",
        "Wes": np.nan,
       }
        

In [4]:
data = pd.Series(data)

In [5]:
data

Dave      dave@google.com
Steve    steve@google.com
Rob        rob@google.com
Wes                   NaN
dtype: object

In [6]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [7]:
data.str.contains("gmail")

Dave     False
Steve    False
Rob      False
Wes        NaN
dtype: object

In [8]:
data_as_string_ext = data.astype("string")

In [9]:
data_as_string_ext

Dave      dave@google.com
Steve    steve@google.com
Rob        rob@google.com
Wes                  <NA>
dtype: string

In [10]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve    False
Rob      False
Wes       <NA>
dtype: boolean

In [11]:
pattern = r"([A-Z0-9._%=-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [12]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave      [(dave, google, com)]
Steve    [(steve, google, com)]
Rob        [(rob, google, com)]
Wes                         NaN
dtype: object

In [13]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [14]:
matches

Dave      (dave, google, com)
Steve    (steve, google, com)
Rob        (rob, google, com)
Wes                       NaN
dtype: object

In [15]:
matches.iloc[1]

('steve', 'google', 'com')

In [16]:
matches.get("Dave")

('dave', 'google', 'com')

In [17]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [18]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve  google  com
Rob      rob  google  com
Wes      NaN     NaN  NaN

In [19]:
data.str.contains(pattern, flags=re.IGNORECASE)

/tmp/ipykernel_4689/1684645838.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  data.str.contains(pattern, flags=re.IGNORECASE)


Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [20]:
data.str.count(pattern, flags=re.IGNORECASE)

Dave     1.0
Steve    1.0
Rob      1.0
Wes      NaN
dtype: float64

True

<h3 style="color:blue">7.5 Categorical Data</h3>

In [38]:
values = pd.Series(["alpha", "orange", "apple", "apple"] * 2)

In [39]:
values

0     alpha
1    orange
2     apple
3     apple
4     alpha
5    orange
6     apple
7     apple
dtype: object

In [44]:
values.unique()

array(['alpha', 'orange', 'apple'], dtype=object)

In [45]:
pd.unique(values)

array(['alpha', 'orange', 'apple'], dtype=object)

In [46]:
pd.value_counts(values)

/tmp/ipykernel_4689/3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


apple     4
alpha     2
orange    2
Name: count, dtype: int64

In [47]:
values.value_counts()

apple     4
alpha     2
orange    2
Name: count, dtype: int64

In [49]:
dim = pd.Series(["apple", "orange"])
# Category listing of values: "apple" = dim[0], "orange" = dim[1]

In [54]:
values = pd.Series([0, 1, 0, 0] * 2) 
# Category codes representing the Series ["apple", "orange", "apple", "apple"]
# that can be mapped to the "dim" Series.

In [52]:
dim.take(values) # 

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

<h3 style="color:purple">Categorical Extension Type in pandas</h3>

In [24]:
fruits = ["apple", "orange", "apple", "apple"] * 2

In [25]:
N = len(fruits)

In [41]:
rng = np.random.default_rng(seed=12345)

In [42]:
df = pd.DataFrame({"fruit": fruits,
    "basket_id": np.arange(N),
    "count": rng.integers(3, 15, size=N),
    "weight": rng.uniform(0, 4, size=N)}, 
    columns=["basket_id", "fruit", "count", "weight"])

In [43]:
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [44]:
fruit_cat = df["fruit"].astype('category')

In [45]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [46]:
c = fruit_cat.array

In [47]:
type(c)

pandas.core.arrays.categorical.Categorical

In [48]:
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']

In [49]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [50]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [51]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [52]:
df["fruit"] = df["fruit"].astype('category')

In [53]:
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [55]:
my_categories = pd.Categorical(["foo", "bar", "baz", "foo", "bar"])

In [57]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [59]:
categories = ["foo", "bar", "baz"]

In [60]:
codes = [0, 1, 2, 0, 0, 1]

In [61]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [62]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [63]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [64]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

<h3 style="color:purple">Computations with Categoricals</h3>

In [76]:
rng = np.random.default_rng(seed=12345)

In [77]:
draws = rng.standard_normal(1000)

In [78]:
draws[:5].round(4)

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

In [79]:
bins = pd.qcut(draws, 4)

In [80]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [81]:
bins = pd.qcut(draws, 4, labels=["Q1", "Q2", "Q3", "Q4"])

In [82]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [83]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [85]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [86]:
bins = pd.Series(bins, name='quartile')

In [100]:
results = (pd.Series(draws)
           .groupby(bins, observed=False)
           .agg(['count', 'min', 'max', 'mean', 'std'])
           .reset_index())

In [101]:
results

quartile  count       min       max      mean       std
0       Q1    250 -3.119609 -0.678494 -1.294347  0.511478
1       Q2    250 -0.673305  0.008009 -0.303875  0.203074
2       Q3    250  0.018753  0.686183  0.343512  0.191344
3       Q4    250  0.688282  3.211418  1.287744  0.491929

In [103]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

<h4 style="color:green">Better Performance with Categoricals</h4>